name: foxbit_hiring_test_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_clean_architecture: ^6.0.1
  get_it: ^8.0.3
  intl: ^0.20.2
  rxdart: ^0.27.7
  web_socket_channel: ^2.2.0

dev_dependencies:

  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter

  lint: 2.3.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/